---
title: "Grindstone 100"
author: "Daniel Spakowicz"
date: "8/3/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("rvest")

library(rvest)
library(lubridate)
```

First I'll read in the previous year's results and format the columns.

```{r}
# Grindstone 2016 results page 
# keeps giving 404 error
url <- "http://apps.eco-xsports.com/reports.php?race=1&year=2016"

x <- read.table("grindstone_2016.tsv", sep = "\t", fill = TRUE, header = TRUE)

times <- hms(x$Time)

asmin <- hour(times)*60 + minute(times) + second(times)/60
as.hour <- asmin/60
```

```{r}
hist(as.hour)
abline(v = median(as.hour))
```

In the Laurel Highlands Ultra my percentile finish was just over 30. If I apply that here my predicted finish is 
```{r}
pred_time <- quantile(as.hour, 0.317757)
pred_time
```

```{r}
split <- pred_time * 60 / 100
split
```

Even splits are 17 min/mile.

What time will I reach North River Gap (mile 65.33)? The places where I could pick up Adam are 51, 65 or 81, so I assume he'll want to do 65 and hobble in the last 35 with me.

```{r}
# Pace is in minutes/mile
TimeAtMile <- function(mile, pace) {
  tmp <- mile * pace/60
  t2 <- 18 + tmp - 24
  return(t2)
}

TimeAtMile(65.33, split)
```

```{r}
TimeAtMile(80.35, split)
```

```{r}
TimeAtMile(22.11, split)
```

```{r}
x <- read.table("grindstone-aid-stations.txt", sep = "\t")

header <- c("#", "Aid Station Name", "Location", "Seg Distance", "Mileage", "Crew Access", "Drop Bags", "Record Pace", "20 Hour Time", "Last Runner", "38-Hour Cutoff", "Elevation", "lat", "lng")

names(x) <- header



start.time <- as.POSIXct("2017-10-06 18:00", tz = "EST", format = "%F %R")

time_at_aid <- function(start.time, aid.locations, min.mile) {
  duration <- aid.locations * min.mile
  secs <- round(duration * 60, 0)
  out <- format(start.time + secs, "%H:%M")
  return(out)
}

x$"15min/mile pace" <- time_at_aid(start.time, x$Mileage, 15)
x$"17min/mile pace" <- time_at_aid(start.time, x$Mileage, split)
x$"19min/mile pace" <- time_at_aid(start.time, x$Mileage, 19)
x$"20min/mile pace" <- time_at_aid(start.time, x$Mileage, 20)

# Reformat the cutoff column to unify it
x$`38-Hour Cutoff` <- strptime(x$`38-Hour Cutoff`, format = "%I:%M %p")
x$`38 hour cutoff` <- format(x$`38-Hour Cutoff`,"%H:%M")

y <- x
y$`#` <- y$`Record Pace` <- y$`lat` <- y$`lng` <- y$`Last Runner` <- y$`20 Hour Time` <- y$`38-Hour Cutoff` <- NULL


write.csv(y, "grindstone-pacing.csv")
```
